# Generated by Django 4.2.6 on 2023-11-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_address_remove_student_forfait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Secretary'), (3, 'Insctructor'), (4, 'Student')], default='Admin', max_length=30),
        ),
    ]
