# Generated by Django 4.2.6 on 2023-11-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='forfait',
            field=models.FloatField(default=0),
        ),
    ]
