# Generated by Django 4.2.6 on 2023-11-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_forfait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='forfait',
            field=models.IntegerField(default=0),
        ),
    ]
